"""Initial schema with BIGINT PKs

Revision ID: c5c4393c88e3
Revises: 
Create Date: 2026-02-14 18:22:35.454419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c4393c88e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='대학교 고유 식별자'),
    sa.Column('semester', sa.String(length=100), nullable=False, comment='모집 학기'),
    sa.Column('region', sa.String(length=100), nullable=False, comment='학교가 위치한 지역 (예: Europe, Asia)'),
    sa.Column('nation', sa.String(length=100), nullable=False, comment='학교가 속한 국가'),
    sa.Column('name_kor', sa.String(length=255), nullable=False, comment='대학교 한글 명칭'),
    sa.Column('name_eng', sa.String(length=255), nullable=False, comment='대학교 영문 명칭'),
    sa.Column('min_gpa', sa.Float(), nullable=False, comment='지원을 위한 최소 GPA'),
    sa.Column('significant_note', sa.Text(), nullable=True, comment='주요사항'),
    sa.Column('remark', sa.Text(), nullable=False, comment='기타 참고사항 (비고)'),
    sa.Column('available_majors', sa.Text(), nullable=True, comment='교환학생 수강 가능한 전공 목록'),
    sa.Column('website_url', sa.Text(), nullable=True, comment='공식 홈페이지 주소'),
    sa.Column('is_exchange', sa.Boolean(), nullable=False, comment='교환학생 파견 가능 여부'),
    sa.Column('is_visit', sa.Boolean(), nullable=False, comment='방문학생 파견 가능 여부'),
    sa.Column('has_review', sa.Boolean(), nullable=False, comment='교환학생 수기 존재 여부'),
    sa.Column('review_year', sa.String(length=50), nullable=True, comment='수기 연도 (예: 2018, 2013-2019)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_university_name_kor', 'university', ['name_kor'], unique=False)
    op.create_index('idx_university_nation', 'university', ['nation'], unique=False)
    op.create_index('idx_university_region', 'university', ['region'], unique=False)
    op.create_table('language_requirement',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='어학 요구사항 고유 식별자'),
    sa.Column('university_id', sa.BigInteger(), nullable=False, comment='대학교 ID'),
    sa.Column('language_group', sa.String(length=50), nullable=False, comment='언어권 분류 (ENGLISH, JAPANESE 등)'),
    sa.Column('exam_type', sa.String(length=50), nullable=False, comment='시험 종류 (TOEFL, IELTS, JLPT 등)'),
    sa.Column('min_score', sa.Float(), nullable=False, comment='요구되는 최소 점수'),
    sa.Column('level_code', sa.String(length=50), nullable=True, comment='레벨/등급 (예: B2, N2 등)'),
    sa.Column('is_available', sa.Boolean(), nullable=False, comment='해당 시험 인정 여부'),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lang_req_exam_type', 'language_requirement', ['exam_type'], unique=False)
    op.create_index('idx_lang_req_university_id', 'language_requirement', ['university_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lang_req_university_id', table_name='language_requirement')
    op.drop_index('idx_lang_req_exam_type', table_name='language_requirement')
    op.drop_table('language_requirement')
    op.drop_index('idx_university_region', table_name='university')
    op.drop_index('idx_university_nation', table_name='university')
    op.drop_index('idx_university_name_kor', table_name='university')
    op.drop_table('university')
    # ### end Alembic commands ###
