"""Drop thumbnail_url and available_semester from University

Revision ID: e56fde3c6997
Revises: 002_restructure_universities
Create Date: 2026-02-14 13:51:48.748385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56fde3c6997'
down_revision: Union[str, None] = '001_restructure_language_scores'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'thumbnail_url')
    op.drop_column('university', 'available_semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('available_semester', sa.String(length=100), nullable=True, comment='파견 가능한 학기 (예: Fall, Spring)'))
    op.add_column('university', sa.Column('thumbnail_url', sa.Text(), nullable=True, comment='학교 로고 또는 대표 이미지'))
    # ### end Alembic commands ###
